### ISSUE TITLE
Unlocking 4K recording, is it possible?

### ISSUE THREAD

**Issue by gingerboy92** [LinuxPanda/android_kernel_rosy#1]
https://github.com/LinuxPanda/android_kernel_rosy/blob/fde6838ad820e9577c1e2ac141a0008be438eed2/drivers/clk/msm/clock-gcc-8953.c#L3733
if i'm not wrong, this part checks for the soc bin and apply the faster ftbl_vcodec0_clk_src_540MHz table if it's on sd625. is there anything else stopping us from enabling 4K recording if we use ftbl_vcodec0_clk_src_540MHz for sdm450 too? 
sorry if i'm doing this the wrong way. i'm not really good with github

**Comment by LinuxPanda** [comment]
To be honest, I have no idea. I don't mess with kernel unless I have a little idea of what I'm doing.

> is there anything else stopping us from enabling 4K recording

I think In the device tree, some configs are needed while building ROM.

* 4K recording support in media profile.
* 4K recording support in OSS Camera hal, since we use OSS camera hal.

And the camera blobs are still from Oreo, so I'm not sure.

If you do a search for "4k video recording" then you can check commits to get an idea. :)
